name: Autojson main

on:
  workflow_dispatch: 
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *' # Runs at the start of every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Grant execute permission for script
        run: chmod +x *.sh

      - name: Generate JSON file
        run: ./pif.sh -p

      - name: Check differences in pif.json
        run: |
          if git diff --exit-code pif.json; then
            echo "pif.json is the same, no need to commit."
          else
            git config --global user.name "daboynb"
            git config --global user.email "username@users.noreply.github.com"
            git add pif.json
            git add Readme.md
            git commit -m "Update pif.json"
            git push
          fi
